/**
 * @file Automatically generated by barrelsby.
 */

export * from './field-change-type.model';
export * from './field-update.model';
export * from './field-updates.model';
export * from './identifiable.model';
export * from './object-updates.actions';
export * from './object-updates.effects.spec';
export * from './object-updates.effects';
export * from './object-updates.reducer.spec';
export * from './object-updates.reducer';
export * from './object-updates.service.spec';
export * from './object-updates.service.stub';
export * from './object-updates.service';
export * from './patch-operation-service/index';
