/**
 * @file Automatically generated by barrelsby.
 */

export * from './vocabulary-entry-details.data.service.spec';
export * from './vocabulary-entry-details.data.service';
export * from './vocabulary.data.service.spec';
export * from './vocabulary.data.service';
export * from './vocabulary.service.spec';
export * from './vocabulary.service';
export * from './models/index';
