export enum SubmissionResourceType {
  Bundle = 'bundle',
  Bitstream = 'bitstream',
  BitstreamFormat = 'bitstreamformat',
  Item = 'item',
  Collection = 'collection',
  Community = 'community',
  ResourcePolicy = 'resourcePolicy',
  License = 'license',
  EPerson = 'eperson',
  Group = 'group',
  WorkspaceItem = 'workspaceitem',
  WorkflowItem = 'workflowitem',
  SubmissionDefinitions = 'submissiondefinitions',
  SubmissionDefinition = 'submissiondefinition',
  SubmissionForm = 'submissionform',
  SubmissionForms = 'submissionforms',
  SubmissionSections = 'submissionsections',
  SubmissionSection = 'submissionsection',
  Authority = 'authority'
}
