import { Component } from '@angular/core';
import { MatIconRegistry } from '@angular/material/icon';
import { DomSanitizer } from '@angular/platform-browser';
import { HeaderService } from './commons/services/Header/header.service';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'trip';
  constructor(
    private iconRegistry: MatIconRegistry,
    private domSanitizer: DomSanitizer,
    private headerService: HeaderService
  ) {this.headerService.showHeader = true;
    [
      'twitter',
      'edit',
      'facebook',
      'instagram',
      'location-red',
      'location-red-line',
      'date',
      'duration',
      'back-outline',
      'budget',
      'interests',
      'mode-transport',
      'right-arrow',
      'star',
      'time',
      'edit',
      'delete',
      'map',
      'walk-fill',
      'rainy',
      'partly-cloudy',
      'notification',
      'white-notification',
      'chat',
      'white-chat',
      'share',
      'save',
      'Itinerary',
      'flight',
      'hotel',
      'search-outline',
      'hotels',
      'booking',
      'airbnb',
      'link-outline',
      'tripon-ticket',
      'user-add',
      'book-myself',
      'menu-icon',
      'close-outline',
      'trip-bag',
      'location-outline',
      'date-outline',
      'people-outline',
      'activity-outline',
      'search-outline-bold',
      'round-user',
      'round-two-user',
      'total-user',
      'city-budget',
      'gen-star',
      'ticket',
      'food',
      'menu-line',
      'cancel-round-red',
      'pending-fill',
      'cancel-fill',
      'trip-cancel-white',
      'success-round-fill',
      'download-ticket',
      'invoice',
      'invoice-black',
      'my-booked-trips',
      'my-profile',
      'my-companions',
      'payment-details',
      'my-favourites-trips',
      'settings',
      'logout',
      'done',
      'close',
      'chat-black',
      'master-card',
      'visa_card',
      'add-card',
      'like',
      'form-to',
      'days-menu',
      'group-trip-bag',
      'book-ticket',
      'arrow-right-outline',
      'home-outline',
      'feeds-outline',
      'my-trips-outline',
      'budget-plan-outline',
      'chat-outline',
      'add-outline',
      'green-right-done',
      'sent-round',
      'emoji',
      'attache-file',
      'picture',
      'notification-outline',
      'user-outline',
      'feeds-outline-menu',
      'chat-menu',
      'budget-planner-menu',
      'user-outline-menu',
      'person-outline',
      'location-input',
      'user-group-outline',
      'alert-msg',
      'info-msg',
      'success-msg',
      'warning-msg'
    ].forEach(key =>
      this.iconRegistry.addSvgIcon(
        'vite_' + key,
        this.domSanitizer.bypassSecurityTrustResourceUrl(
          `./assets/icons/${key}.svg`,
        ),
      ),
    );
  }
}
