export enum ResourceType {
  DSpaceObject = 'dspaceobject',
  Bundle = 'bundle',
  Bitstream = 'bitstream',
  BitstreamFormat = 'bitstreamformat',
  Item = 'item',
  Collection = 'collection',
  Community = 'community',
  EPerson = 'eperson',
  Group = 'group',
  ResourcePolicy = 'resourcePolicy',
  MetadataSchema = 'metadataschema',
  MetadataField = 'metadatafield',
  Relationship = 'relationship',
  RelationshipType = 'relationshiptype',
  ItemType = 'entitytype',
  License = 'license',
  Workflowitem = 'workflowitem',
  Workspaceitem = 'workspaceitem',
  SubmissionDefinitions = 'submissiondefinitions',
  SubmissionDefinition = 'submissiondefinition',
  SubmissionForm = 'submissionform',
  SubmissionForms = 'submissionforms',
  SubmissionSections = 'submissionsections',
  SubmissionSection = 'submissionsection',
  ClaimedTask = 'claimedtask',
  PoolTask = 'pooltask'
}
