export enum ResourceType {
  DSpaceObject = 'dspaceobject',
  Bundle = 'bundle',
  Bitstream = 'bitstream',
  BitstreamFormat = 'bitstreamformat',
  Item = 'item',
  Collection = 'collection',
  Community = 'community',
  Eperson = 'eperson',
  Group = 'group',
  ResourcePolicy = 'resourcePolicy',
  License = 'license',
  ClaimedTask = 'claimedtask',
  PoolTask = 'pooltask',
  Workflowitem = 'workflowitem',
  Workspaceitem = 'workspaceitem',
}
