/**
 * @file Automatically generated by barrelsby.
 */

export * from './bulk-access-config-data.service';
export * from './coar-notify-config-data.service.spec';
export * from './coar-notify-config-data.service';
export * from './config-data.service.spec';
export * from './config-data.service';
export * from './submission-accesses-config-data.service';
export * from './submission-forms-config-data.service';
export * from './submission-uploads-config-data.service';
export * from './models/index';
