/**
 * @file Automatically generated by barrelsby.
 */

export * from './metadata-patch-operation.service.spec';
export * from './metadata-patch-operation.service';
export * from './patch-operation.service';
export * from './operations/index';
