/**
 * @file Automatically generated by barrelsby.
 */

export * from './claimed-task-data.service.spec';
export * from './claimed-task-data.service';
export * from './pool-task-data.service.spec';
export * from './pool-task-data.service';
export * from './task-response-parsing.service';
export * from './tasks.service.spec';
export * from './tasks.service';
export * from './models/index';
