name: Erase database

on:
  workflow_call:
    inputs:
      INSTANCE:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      INSTANCE:
        required: true
        default: '5'
        type: choice
        options:
          - '5'
          - '8'


jobs:
  recreate_db:
    runs-on: dspace-dep-1
    timeout-minutes: 5
    env:
      INSTANCE: ${{ inputs.INSTANCE }}
      NAME: dspace-${{ inputs.INSTANCE }}
    steps:

      - name: stop and remove containers
        run: |
          docker stop dspacesolr$INSTANCE dspacedb$INSTANCE dspace$INSTANCE dspace-angular$INSTANCE || true
          docker rm   dspacesolr$INSTANCE dspacedb$INSTANCE dspace$INSTANCE dspace-angular$INSTANCE || true

      - name: remove volumes
        if: '!cancelled()'
        run: |
          # be sure to have INSTANCE set
          if [[ "x${{ env.NAME }}" != "dspace-" ]]; then
            docker volume rm $(docker volume ls --filter name="${{ env.NAME }}_" -q) || true
          fi;
