name: Import DSpace v5

on:
  workflow_dispatch:
    inputs:
      INSTANCE:
        required: true
        default: '8'
        type: choice
        options:
          - '8'

jobs:
  import:
    runs-on: dspace-dep-1
    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/erase-db
        with:
          INSTANCE: ${{ env.INSTANCE }}
          NAME: dspace-${{ env.INSTANCE }}

      - name: deploy dspace-import on dev-5
        working-directory: build-scripts/run/
        run: |
          ENVFILE=/opt/dspace-envs/.env.dspace.imported.dev-5 ./start.sh dspace-$INSTANCE
          /bin/bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://dev-5.pc:8$INSTANCE/server/api)" != "200" ]]; do sleep 5; done'

      - uses: ./.github/actions/import-db
        if: github.event.inputs.IMPORT != false
        with:
          INSTANCE: ${{ env.INSTANCE }}
          DATADIR: /opt/dspace-data/clarin-dspace/
